# The list of stocks that are part of the Dow Jones Industrial Average index
# and their weights, as of 2025-01-15
from typing import List

# removing two stocks added during the last 5 years
dow_jones_stocks = [
    {"Company": "Goldman Sachs Group Inc", "Ticker": "GS", "Weight": 8.26},
    {"Company": "UnitedHealth Group Inc", "Ticker": "UNH", "Weight": 7.86},
    {"Company": "Microsoft Corp", "Ticker": "MSFT", "Weight": 6.01},
    {"Company": "Home Depot Inc", "Ticker": "HD", "Weight": 5.68},
    {"Company": "Caterpillar Inc", "Ticker": "CAT", "Weight": 5.37},
    #    {"Company": "Sherwin-Williams Co", "Ticker": "SHW", "Weight": 4.94},
    {"Company": "Salesforce Inc", "Ticker": "CRM", "Weight": 4.68},
    {"Company": "Visa Inc Class A Shares", "Ticker": "V", "Weight": 4.47},
    {"Company": "American Express Co", "Ticker": "AXP", "Weight": 4.34},
    {"Company": "McDonald's Corp", "Ticker": "MCD", "Weight": 4.07},
    {"Company": "Amgen Inc", "Ticker": "AMGN", "Weight": 3.86},
    {"Company": "JPMorgan Chase & Co", "Ticker": "JPM", "Weight": 3.58},
    {"Company": "Travelers Cos Inc", "Ticker": "TRV", "Weight": 3.42},
    {"Company": "Apple Inc", "Ticker": "AAPL", "Weight": 3.37},
    {"Company": "Honeywell International Inc", "Ticker": "HON", "Weight": 3.16},
    {"Company": "Amazon.com Inc", "Ticker": "AMZN", "Weight": 3.15},
    {"Company": "Intl Business Machines Corp", "Ticker": "IBM", "Weight": 3.15},
    {"Company": "Boeing Co", "Ticker": "BA", "Weight": 2.41},
    {"Company": "Procter & Gamble Co", "Ticker": "PG", "Weight": 2.31},
    {"Company": "Chevron Corp", "Ticker": "CVX", "Weight": 2.27},
    {"Company": "Johnson & Johnson", "Ticker": "JNJ", "Weight": 2.09},
    {"Company": "3M Co", "Ticker": "MMM", "Weight": 1.98},
    #   {"Company": "Nvidia Corp", "Ticker": "NVDA", "Weight": 1.90},
    {"Company": "Walt Disney Co", "Ticker": "DIS", "Weight": 1.56},
    {"Company": "Merck & Co. Inc.", "Ticker": "MRK", "Weight": 1.44},
    {"Company": "Walmart Inc", "Ticker": "WMT", "Weight": 1.31},
    {"Company": "Nike Inc Cl B", "Ticker": "NKE", "Weight": 1.03},
    {"Company": "Coca-Cola Co", "Ticker": "KO", "Weight": 0.90},
    {"Company": "Cisco Systems Inc", "Ticker": "CSCO", "Weight": 0.86},
    {"Company": "Verizon Communications Inc", "Ticker": "VZ", "Weight": 0.55},
]


nasdaq_100 = [
    {"Company": "Apple Inc.", "Ticker": "AAPL", "Weight": 9.26},
    {"Company": "Microsoft Corp.", "Ticker": "MSFT", "Weight": 8.26},
    {"Company": "Amazon.com Inc.", "Ticker": "AMZN", "Weight": 6.01},
    {"Company": "NVIDIA Corp.", "Ticker": "NVDA", "Weight": 5.68},
    {"Company": "Alphabet Inc. (Class C)", "Ticker": "GOOG", "Weight": 5.37},
    {"Company": "Alphabet Inc. (Class A)", "Ticker": "GOOGL", "Weight": 4.94},
    {"Company": "Meta Platforms Inc.", "Ticker": "META", "Weight": 4.68},
    {"Company": "Tesla Inc.", "Ticker": "TSLA", "Weight": 4.47},
    {"Company": "Broadcom Inc.", "Ticker": "AVGO", "Weight": 4.34},
    {"Company": "Costco Wholesale Corp.", "Ticker": "COST", "Weight": 4.07},
    {"Company": "PepsiCo Inc.", "Ticker": "PEP", "Weight": 3.86},
    {"Company": "Adobe Inc.", "Ticker": "ADBE", "Weight": 3.58},
    {"Company": "Cisco Systems Inc.", "Ticker": "CSCO", "Weight": 3.42},
    {"Company": "Netflix Inc.", "Ticker": "NFLX", "Weight": 3.37},
    {"Company": "Intel Corp.", "Ticker": "INTC", "Weight": 3.16},
    {"Company": "Comcast Corp.", "Ticker": "CMCSA", "Weight": 3.15},
    {"Company": "Texas Instruments Inc.", "Ticker": "TXN", "Weight": 2.41},
    {"Company": "Advanced Micro Devices Inc.", "Ticker": "AMD", "Weight": 2.31},
    {"Company": "QUALCOMM Inc.", "Ticker": "QCOM", "Weight": 2.27},
    {"Company": "PayPal Holdings Inc.", "Ticker": "PYPL", "Weight": 2.09},
    {"Company": "Intuit Inc.", "Ticker": "INTU", "Weight": 1.98},
    {"Company": "Honeywell International Inc.", "Ticker": "HON", "Weight": 1.90},
    {"Company": "Starbucks Corp.", "Ticker": "SBUX", "Weight": 1.56},
    {"Company": "Mondelez International Inc.", "Ticker": "MDLZ", "Weight": 1.44},
    {"Company": "Booking Holdings Inc.", "Ticker": "BKNG", "Weight": 1.31},
    {"Company": "Analog Devices Inc.", "Ticker": "ADI", "Weight": 1.03},
    {"Company": "Lam Research Corp.", "Ticker": "LRCX", "Weight": 0.90},
    {"Company": "Micron Technology Inc.", "Ticker": "MU", "Weight": 0.86},
    {"Company": "Automatic Data Processing Inc.", "Ticker": "ADP", "Weight": 0.55},
    {"Company": "Marvell Technology Inc.", "Ticker": "MRVL", "Weight": 0.55},
    {"Company": "KLA Corp.", "Ticker": "KLAC", "Weight": 0.55},
    {"Company": "Applied Materials Inc.", "Ticker": "AMAT", "Weight": 0.55},
    {"Company": "Palo Alto Networks Inc.", "Ticker": "PANW", "Weight": 0.55},
    {"Company": "CSX Corp.", "Ticker": "CSX", "Weight": 0.55},
    {"Company": "Cintas Corp.", "Ticker": "CTAS", "Weight": 0.55},
    {"Company": "Intuitive Surgical Inc.", "Ticker": "ISRG", "Weight": 0.55},
    {"Company": "Gilead Sciences Inc.", "Ticker": "GILD", "Weight": 0.55},
    {"Company": "Cadence Design Systems Inc.", "Ticker": "CDNS", "Weight": 0.55},
    {"Company": "NXP Semiconductors NV", "Ticker": "NXPI", "Weight": 0.55},
    {"Company": "Lululemon Athletica Inc.", "Ticker": "LULU", "Weight": 0.55},
    {"Company": "Dexcom Inc.", "Ticker": "DXCM", "Weight": 0.55},
    {"Company": "Vertex Pharmaceuticals Inc.", "Ticker": "VRTX", "Weight": 0.55},
    {"Company": "O'Reilly Automotive Inc.", "Ticker": "ORLY", "Weight": 0.55},
    {"Company": "Regeneron Pharmaceuticals Inc.", "Ticker": "REGN", "Weight": 0.55},
    {"Company": "Copart Inc.", "Ticker": "CPRT", "Weight": 0.55},
    {"Company": "Microchip Technology Inc.", "Ticker": "MCHP", "Weight": 0.55},
    {"Company": "Ross Stores Inc.", "Ticker": "ROST", "Weight": 0.55},
    {"Company": "Workday Inc.", "Ticker": "WDAY", "Weight": 0.55},
    {"Company": "PDD Holdings Inc.", "Ticker": "PDD", "Weight": 0.55},
    {"Company": "Atlassian Corp.", "Ticker": "TEAM", "Weight": 0.55},
    {"Company": "Datadog Inc.", "Ticker": "DDOG", "Weight": 0.55},
    {"Company": "Old Dominion Freight Line Inc.", "Ticker": "ODFL", "Weight": 0.55},
    {"Company": "Fortinet Inc.", "Ticker": "FTNT", "Weight": 0.55},
    {"Company": "Marriott International Inc.", "Ticker": "MAR", "Weight": 0.55},
    {"Company": "Paychex Inc.", "Ticker": "PAYX", "Weight": 0.55},
    {"Company": "IDEXX Laboratories Inc.", "Ticker": "IDXX", "Weight": 0.55},
    {"Company": "Synopsys Inc.", "Ticker": "SNPS", "Weight": 0.55},
    {"Company": "MercadoLibre Inc.", "Ticker": "MELI", "Weight": 0.55},
    {"Company": "Align Technology Inc.", "Ticker": "ALGN", "Weight": 0.55},
    {"Company": "Zoom Video Communications Inc.", "Ticker": "ZM", "Weight": 0.55},
]


sp_midcap_400_top50 = [
    {"Company": "Fair Isaac Corp.", "Ticker": "FICO"},
    {"Company": "Bio-Techne Corp.", "Ticker": "TECH"},
    {"Company": "IDEX Corp.", "Ticker": "IEX"},
    {"Company": "Cognex Corp.", "Ticker": "CGNX"},
    {"Company": "Teledyne Technologies Inc.", "Ticker": "TDY"},
    {"Company": "Zebra Technologies Corp. Class A", "Ticker": "ZBRA"},
    {"Company": "West Pharmaceutical Services Inc.", "Ticker": "WST"},
    {"Company": "MSCI Inc.", "Ticker": "MSCI"},
    {"Company": "CoStar Group Inc.", "Ticker": "CSGP"},
    {"Company": "MarketAxess Holdings Inc.", "Ticker": "MKTX"},
    {"Company": "Pool Corp.", "Ticker": "POOL"},
    {"Company": "Tyler Technologies Inc.", "Ticker": "TYL"},
    {"Company": "EPAM Systems Inc.", "Ticker": "EPAM"},
    {"Company": "DexCom Inc.", "Ticker": "DXCM"},
    {"Company": "Chipotle Mexican Grill Inc.", "Ticker": "CMG"},
    {"Company": "Garmin Ltd.", "Ticker": "GRMN"},
    {"Company": "FactSet Research Systems Inc.", "Ticker": "FDS"},
    {"Company": "Jack Henry & Associates Inc.", "Ticker": "JKHY"},
    {"Company": "Lattice Semiconductor Corp.", "Ticker": "LSCC"},
    {"Company": "Entegris Inc.", "Ticker": "ENTG"},
    {"Company": "Old Dominion Freight Line Inc.", "Ticker": "ODFL"},
    {"Company": "Fortinet Inc.", "Ticker": "FTNT"},
    {"Company": "Ceridian HCM Holding Inc.", "Ticker": "CDAY"},
    {"Company": "Generac Holdings Inc.", "Ticker": "GNRC"},
    {"Company": "AvalonBay Communities Inc.", "Ticker": "AVB"},
    {"Company": "W.R. Berkley Corp.", "Ticker": "WRB"},
    {"Company": "Cintas Corp.", "Ticker": "CTAS"},
    {"Company": "Align Technology Inc.", "Ticker": "ALGN"},
    {"Company": "SVB Financial Group", "Ticker": "SIVB"},
    {"Company": "Bio-Rad Laboratories Inc. Class A", "Ticker": "BIO"},
    {"Company": "Lennox International Inc.", "Ticker": "LII"},
    {"Company": "First Solar Inc.", "Ticker": "FSLR"},
    {"Company": "Palo Alto Networks Inc.", "Ticker": "PANW"},
    {"Company": "Keysight Technologies Inc.", "Ticker": "KEYS"},
    {"Company": "Westinghouse Air Brake Technologies Corp.", "Ticker": "WAB"},
    {"Company": "TransDigm Group Inc.", "Ticker": "TDG"},
    {"Company": "Copart Inc.", "Ticker": "CPRT"},
    {"Company": "Verisk Analytics Inc.", "Ticker": "VRSK"},
    {"Company": "ANSYS Inc.", "Ticker": "ANSS"},
    {"Company": "Synopsys Inc.", "Ticker": "SNPS"},
    {"Company": "CDW Corp.", "Ticker": "CDW"},
    {"Company": "Mettler-Toledo International Inc.", "Ticker": "MTD"},
    {"Company": "Amphenol Corp. Class A", "Ticker": "APH"},
    {"Company": "Roper Technologies Inc.", "Ticker": "ROP"},
    {"Company": "Motorola Solutions Inc.", "Ticker": "MSI"},
    {"Company": "IQVIA Holdings Inc.", "Ticker": "IQV"},
    {"Company": "Edwards Lifesciences Corp.", "Ticker": "EW"},
    {"Company": "ServiceNow Inc.", "Ticker": "NOW"},
    {"Company": "Illumina Inc.", "Ticker": "ILMN"},
]


_group2stocks = dict(
    dowjones=dow_jones_stocks, nasdaq=nasdaq_100, spmid=sp_midcap_400_top50
)


def get_tickers(group: str, num_tickers: int = -1) -> List[str]:
    tickers = [el["Ticker"] for el in _group2stocks[group]]
    tickers = tickers[0:num_tickers] if num_tickers > 0 else tickers
    return tickers
